-- CREATE DATABASE
CREATE DATABASE MY_SQL_DB;


-- USE DATABASE
USE MY_SQL_DB;


-- CREATE TABLE
CREATE TABLE STUDENTS (
	ROLL_NUMBER INT NOT NULL PRIMARY KEY,
	FIRST_NAME VARCHAR(30) NOT NULL,
	LAST_NAME VARCHAR(30) NOT NULL,
	AGE INT NOT NULL,
	PHONE VARCHAR(10),
	EMAIL VARCHAR(30)
);


-- INSERT DATA 
INSERT INTO STUDENTS VALUES (001, 'NISARG', 'PATEL', 22, '0000000000', 'nisargp@Gmail.com');
INSERT INTO STUDENTS (ROLL_NUMBER, FIRST_NAME, LAST_NAME, AGE, PHONE, EMAIL) 
	VALUES (002, 'SAGAR', 'DEVANI', 22, '9723959942', 'sagarp@Gmail.com');
INSERT INTO STUDENTS (ROLL_NUMBER, FIRST_NAME, LAST_NAME, AGE, PHONE, EMAIL) 
	VALUES (003, 'SMIT', 'PRAJAPATI', 22, '9723959941', 'smitp@Gmail.com'),
		   (004, 'MALAY', 'CHAUDHARI', 22, '9723959940', 'malayc@Gmail.com'),
		   (005, 'KALPIT', 'PRAJAPATI', 22, '9723959944', 'kalpitp@Gmail.com');


--  SELECT DATA
SELECT * FROM STUDENTS;
SELECT ROLL_NUMBER, FIRST_NAME, AGE FROM STUDENTS;
SELECT * FROM STUDENTS WHERE FIRST_NAME = 'NISARG';
SELECT AVG(AGE), FIRST_NAME FROM STUDENTS;


-- UPDATE DATA
UPDATE STUDENTS SET PHONE = '9723959943' WHERE ROLL_NUMBER = 001;
UPDATE STUDENTS SET PHONE = '0000000000', AGE = '24' WHERE ROLL_NUMBER = 003;
UPDATE STUDENTS SET AGE = 23;


--DELETE DATA
DELETE FROM STUDENTS WHERE ROLL_NUMBER=005;
DELETE FROM STUDENTS;


-- DROP TABLE AND DATABASE
DROP DATABASE MY_SQL_DB;
DROP TABLE STUDENTS;



-- SHOW ALL DATABASES, TABLES AND COLUMNS
SELECT * FROM SYS.DATABASES;
SELECT NAME,DATABASE_ID FROM SYS.DATABASES;

SELECT * FROM SYS.TABLES;
SELECT * FROM INFORMATION_SCHEMA.TABLES;

SELECT * FROM SYS.COLUMNS;
SELECT * FROM INFORMATION_SCHEMA.COLUMNS;
SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'STUDENTS';



-- DISTINCT
INSERT INTO STUDENTS (ROLL_NUMBER, FIRST_NAME, LAST_NAME, AGE, PHONE, EMAIL) 
	VALUES (006, 'SMIT', 'PRAJAPATI', 22, '9723959941', 'smitp@Gmail.com'),
		   (007, 'MALAY', 'CHAUDHARI', 22, '9723959940', 'malayc@Gmail.com'),
		   (008, 'KALPIT', 'PRAJAPATI', 22, '9723959944', 'kalpitp@Gmail.com');
SELECT DISTINCT FIRST_NAME FROM STUDENTS;
SELECT DISTINCT FIRST_NAME, LAST_NAME FROM STUDENTS;  -- GIVE THE DISTINCT ROW 
SELECT DISTINCT  ROLL_NUMBER,FIRST_NAME,LAST_NAME,AGE FROM STUDENTS;



-- ORDER BY 
INSERT INTO STUDENTS (ROLL_NUMBER, FIRST_NAME, LAST_NAME, AGE, PHONE, EMAIL) 
	VALUES (009, 'SMIT', 'CHAUDHARI', 22, '9723959941', 'smitp@Gmail.com'),
		   (010, 'MALAY', 'PATEL', 22, '9723959940', 'malayc@Gmail.com'),
		   (011, 'KALPIT', 'DEVANI', 22, '9723959944', 'kalpitp@Gmail.com');
SELECT * FROM STUDENTS ORDER BY FIRST_NAME;
SELECT * FROM STUDENTS ORDER BY FIRST_NAME DESC;
SELECT * FROM STUDENTS ORDER BY FIRST_NAME ASC, LAST_NAME DESC;



-- AND, OR, NOT
SELECT * FROM STUDENTS WHERE FIRST_NAME = 'SMIT' AND LAST_NAME='CHAUDHARI';
SELECT * FROM STUDENTS WHERE FIRST_NAME = 'SMIT' OR LAST_NAME='CHAUDHARI';
SELECT * FROM STUDENTS WHERE NOT FIRST_NAME = 'SMIT';
SELECT * FROM STUDENTS WHERE FIRST_NAME = 'SMIT' AND (LAST_NAME = 'PRAJAPATI' OR LAST_NAME = 'PATEL');



-- NULL
INSERT INTO STUDENTS (ROLL_NUMBER, FIRST_NAME, LAST_NAME, AGE) 
	VALUES (012, 'SMIT', 'PATEL', 22),
		   (013, 'MALAY', 'DEVANI', 22),
		   (014, 'KALPIT', 'PATEL', 22);
SELECT * FROM STUDENTS WHERE PHONE IS NULL;
SELECT * FROM STUDENTS WHERE PHONE IS NOT NULL;



-- TOP
SELECT TOP 3 * FROM STUDENTS;
SELECT TOP 50 PERCENT * FROM STUDENTS;